language: cpp

os:
  - osx
  - linux

sudo: required

services:
  - docker

env:
  - CONDA_RECIPE=ann
    CONDA_VERSION=3
    
  - CONDA_RECIPE=cgal
    CONDA_VERSION=3
    
  - CONDA_RECIPE=libqglviewer
    CONDA_VERSION=3
    
  - CONDA_RECIPE=pyqglviewer
    CONDA_VERSION=3
    
  - CONDA_RECIPE=qhull
    CONDA_VERSION=3

  - CONDA_RECIPE=plantgl
    CONDA_VERSION=3

  - ANACONDA_RELEASE=true

install:
  - git clone https://github.com/openalea/travis-ci.git
  - cd travis-ci
  - source install.sh

before_script:
  - source before_script.sh

script:
  - source script.sh

after_success:
  - source after_success.sh

after_failure:
  - source after_failure.sh

before_deploy:
  - source before_deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  on:
    all_branches: true
  script: bash deploy_script.sh

after_deploy:
  - source after_deploy.sh

after_script:
  - source after_script.sh
