language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
    - os: osx
      osx_image: xcode10.1

sudo: required

services:
  - docker

env:
  - CONDA_RECIPE=openalea.deploy
    CONDA_VERSION=3
    
  - CONDA_RECIPE=ann
    CONDA_VERSION=3
    
  - CONDA_RECIPE=cgal
    CONDA_VERSION=3
    
  - CONDA_RECIPE=libqglviewer
    CONDA_VERSION=3
    
  - CONDA_RECIPE=pyqglviewer
    CONDA_VERSION=3
    
  - CONDA_RECIPE=qhull
    CONDA_VERSION=3

  - CONDA_RECIPE=plantgl
    CONDA_VERSION=3
    
  - CONDA_RECIPE=lpy
    CONDA_VERSION=3
    
  - CONDA_RECIPE=mtg
    CONDA_VERSION=3
    
  - CONDA_RECIPE=plantscan3d
    CONDA_VERSION=3

  - ANACONDA_RELEASE=true

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - git clone https://github.com/openalea/travis-ci.git
  - cd travis-ci
  - source install.sh

before_script:
  - source before_script.sh

script:
  - source script.sh

after_success:
  - source after_success.sh

after_failure:
  - source after_failure.sh

before_deploy:
  - source before_deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  on:
    all_branches: true
  script: bash deploy_script.sh

after_deploy:
  - source after_deploy.sh

after_script:
  - source after_script.sh
